- pkg/controller/actuator_reconcile.go
- pkg/healthcheck/add.go
- pkg/healthcheck/custom_health_check/check_installation_managed_resources.go
This adds a health check also for the installation managed resource that is being created for ContainerRuntime resource.
Fixes #
```improvement operator
Add health check for gvisor installation managed resource.
```
> Add health check for installation managed resource

- .test-defs/TestSuiteGvisorBetaSerial.yaml
Change the current testdefinition from a gardener to a shoot testdefinition as it actually requires a shoot.
```improvement operator
NONE
```
> update test suite to be a shoot test suite

- charts/internal/gvisor-installation/templates/configmap-containerd.yaml
Fix containerd config file version detection.
More info about the configuration file versions can be found at https://containerd.io/releases/#daemon-configuration
Fixes #20 
Opened as draft till #18 is reviewed, approved and merged.
```improvement operator
A bug in the gVisor installation script, that does not properly detect the containerd configuration file version, is now fixed.
```
> Fix containerd config file version detection

- cmd/gardener-extension-runtime-gvisor/app/app.go
Disable cache for secrets
Fixes #
Similar to https://github.com/gardener/gardener-extension-networking-calico/pull/55
```improvement operator
The cache for Secrets has been disabled to decrease the extension controller's memory footprint.
```
> Disable cache for secrets

- Dockerfile
- Makefile
- charts/internal/gvisor-installation/templates/configmap-containerd.yaml
- hack/install-binaries.sh
Update runsc and shim binaries to version `20210726`.
Fixes #
Similar to #12 but to more recent version.
Opened as draft till #18 is reviewed, approved and merged.
```improvement operator
The `runsc` and `containerd-shim-runsc-v1` binaries are now updated to verison `20210726`.
```
> Update runsc and shim binaries

- test/integration/container-runtime/container_runtime.go
/area testing
/kind enhancement
Similar to https://github.com/gardener/gardener/issues/4160, currently the integration test can fail/flake because of Docker Hub rate limits
```improvement operator
NONE
```
> Prevent Docker Hub rate limits in the integration test

- cmd/gardener-extension-runtime-gvisor/app/app.go
/area quality
/kind bug
Ref https://github.com/gardener/gardener-extension-networking-calico/pull/42
```bugfix operator
An issue causing runtime-gvisor extension controller to not respect the `--max-concurrent-reconciles` flag is now fixed.
```
> Honor --max-concurrent-reconciles flag

- Makefile
Fixes #34 (Installation image is using wrong tag by default)
Incorrect path was being passed in LD_FILES - a "pkg" element was missing in the path. That resulted in version info not getting applied during build and retaining the hardcoded default - a 0.0.0 version. That default did not correspond to a valid gVisor image version.
NONE
> Fix a bug in the build machinery that was not properly setting the binary version

- .ci/pipeline_definitions
[pipeline] Inject effective version
A follow-up on #35 because, even with that fix, the installed image is still not the expected one. 
When I started the controller version [v0.5.0-dev-5d1f3a4a3f0a6642d1f93c97075afa6f9224b6cc](https://github.com/gardener/gardener-extension-runtime-gvisor/tree/5d1f3a4a3f0a6642d1f93c97075afa6f9224b6cc), I was expecting the installation image to use the tag `v0.5.0-dev-5d1f3a4a3f0a6642d1f93c97075afa6f9224b6cc`, however it is using `v0.5.0-dev`, i.e. the effective version is not used during the build in the pipeline.
```bash
$ kubectl -n kube-system get pod -l app.kubernetes.io/name=containerd-gvisor -o json | jq .items[].spec.containers[].image
"eu.gcr.io/gardener-project/gardener/extensions/runtime-gvisor-installation …
```
> [pipeline] Inject effective version

- .ci/pipeline_definitions
Reverts gardener/gardener-extension-runtime-gvisor#36
This change has broken the verify step due to the different version now in the [example/controller-registration.yaml](https://github.com/gardener/gardener-extension-runtime-gvisor/blob/master/example/controller-registration.yaml)
> Revert "[pipeline] Inject effective version"

- .dockerignore
/kind bug
Currently the `--version` flag reports a dirty GitTreeState even for the head-update build from the current master:
```
$ docker run eu.gcr.io/gardener-project/gardener/extensions/runtime-gvisor:v0.5.0-dev-2e5edbe50fc6d2c44ebfb833157b6f30564f9d63 --version=raw
version.Info{Major:"0", Minor:"5+", GitVersion:"v0.5.0-dev", GitCommit:"2e5edbe50fc6d2c44ebfb833157b6f30564f9d63", GitTreeState:"dirty", BuildDate:"2022-03-03T08:23:56+00:00", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
```
In short, the `get-build-ld-flags.sh` script depends on the `.dockerignore` file to be present during docker build.
https://github.com/gardener/gardener-extension-runtime-gvisor/blob/2e5edbe50fc6d2c44ebfb833157b6f30564f9d63/vendor/github.com/gardener/gardener/hack/get-build-ld-flags.sh#L …
> Fix the GitTreeState reported by the --version flag

- .test-defs/TestSuiteGvisorBetaSerial.yaml
- test/integration/suites/run_suite_test.go
/area testing
/kind bug
1. Currently with `golang:1.16.6` the test execution fails with:
```
vendor/sigs.k8s.io/json/internal/golang/encoding/json/encode.go:1249:12: sf.IsExported undefined (type reflect.StructField has no field or method IsExported)
vendor/sigs.k8s.io/json/internal/golang/encoding/json/encode.go:1255:18: sf.IsExported undefined (type reflect.StructField has no field or method IsExported)
```
To fix the TestDefinition image is updated to go1.17.
2. Next, the test execution failed with:
```
test/integration/suites/run_suite_test.go:57:72: undefined: reporter.NewGardenerESReporter
```
`test/integration/suites/run_suite_test.go` has to be adapted to fix the build failure.
```bugfix developer
An issue causing the integration test execution to fail due to …
```
> Fix integration test TestDefinition

- .test-defs/TestSuiteGvisorBetaSerial.yaml
- test/integration/suites/run_suite_test.go
/kind/bug
/area/testing
Cherry pick of #45 on release-v0.5.
#45: Fix integration test TestDefinition
**Release Notes:**
```bugfix developer
An issue causing the integration test execution to fail due to outdated golang version is now fixed.
```
> [release-v0.5] Automated cherry pick of #45: Fix integration test TestDefinition

- Dockerfile
Changes the base image of the extension to `distroless` and uses a non root user by default.
Fixes #
```noteworthy operator
The extension container now uses `distroless` as a base image.
```
> Change extension's base image to distroless

- charts/internal/gvisor/templates/psp-gvisor.yaml
- charts/internal/gvisor/templates/rbac-gvisor.yaml
- charts/internal/gvisor/values.yaml
- pkg/charts/charts_test.go
- pkg/charts/values.go
- pkg/controller/actuator_reconcile.go
- pkg/controller/controller_test.go
`PodSecurityPolicy` is deprecated and will be disabled in kubernetes v1.25+.
End-users are provided an option to migrate their PSPs before upgrading and disable the `PodSecurityPolicy` admission plugin in the ShootSpec. 
In that case, we should stop deploying our PSPs as well.
- This PR stops deploying PSPs related to `runtime-gvisor` if the plugin is disabled in the Shoot.
Part of https://github.com/gardener/gardener/issues/5250
/area open-source
/kind enhancement
/squash
/hold depends on #55 
```breaking operator
Please make sure you're running gardener@v1.53 or above before upgrading to this version.
```
> Don't deploy `PSP`s when `PodSecurityPolicy` plugin is disabled 

- .golangci.yaml
- .test-defs/TestSuiteGvisorBetaSerial.yaml
- Dockerfile
Update alpine and go version to get rid of:
Alpine issues:
- [CVE-2022-2068](https://nvd.nist.gov/vuln/detail/CVE-2022-2068) 
- [CVE-2022-2097](https://nvd.nist.gov/vuln/detail/CVE-2022-2097)
Go issues:
- [CVE-2022-29526](https://nvd.nist.gov/vuln/detail/CVE-2022-29526)
- [CVE-2022-30634](https://nvd.nist.gov/vuln/detail/CVE-2022-30634)
Fixes #
@danielfoehrKn Could you cut a new release when this PR is merged?
```improvement operator
Updated the alpine base image for the installation pods to 3.16.1.
```
```improvement operator
Golang version is updated to 1.18.5
```
> Update alpine version to 3.16.1 and go version to 1.18.5

- .ci/pipeline_definitions
This PR lets the CI pipeline build multi-arch images including linux/amd64 and linux/arm64 images.
Part of https://github.com/gardener/backlog/issues/19
```other operator
Published docker images for gvisor are now multi-arch ready. They support `linux/amd64` and `linux/arm64`.
```
> Build Multi-Arch Images

- charts/internal/gvisor/templates/runtimeclass-gvisor.yaml
RuntimeClass in the node.k8s.io/v1beta1 API version will no longer be served in v1.25. [Ref](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#runtimeclass-v125)
Part of https://github.com/gardener/gardener/issues/6567
```improvement operator
NONE
```
> Handle `RuntimeClass` `node.k8s.io/v1`

- test/integration/container-runtime/container_runtime.go
This PR updates the `busybox` test images to a multi-arch image.
Part of https://github.com/gardener/backlog/issues/19
```improvement operator
NONE
```
> Use multi-arch image of `busybox`

- charts/internal/gvisor/templates/runtimeclass-gvisor.yaml
- charts/internal/gvisor/values.yaml
- hack/api-reference/config.json
- pkg/charts/charts_test.go
- pkg/charts/values.go
- pkg/controller/actuator_reconcile.go
- pkg/controller/controller_test.go
Part of https://github.com/gardener/gardener-extension-provider-aws/issues/595
```breaking operator
runtime-gvisor no longer supports Shoots with Кubernetes version < 1.17.
```
> Remove support for Shoots with Kubernetes version < 1.17

- Dockerfile
Update `alpine` version to `3.16.2` to mitigate :
[CVE-2022-37434](https://nvd.nist.gov/vuln/detail/CVE-2022-37434)
```improvement operator
Update alpine version to `3.16.2`.
```
> Update alpine version to 3.16.2

- charts/internal/gvisor-installation/templates/daemonset-containerd.yaml
- charts/internal/gvisor/templates/runtimeclass-gvisor.yaml
- hack/api-reference/config.json
Drop support for kubernetes < 1.20 for runtime gvisor extension
Part of https://github.com/gardener/gardener/issues/6911
```other operator
runtime-gvisor no longer supports Shoots with Кubernetes version < 1.20.
```
> Drop support for kubernetes < 1.20 for runtime gvisor extension

- .ci/pipeline_definitions
Assign @gardener/gardener-extension-runtime-gvisor-maintainers  team members as code owners in pipeline definition
Fixes #
cc @marwinski @MrBatschner @danielfoehrKn
cc @JordanJordanov
/invite @ccwienk @zkdev 
```improvement operator
```
> Assign gvisor team members as code owners in pipeline definition

- cmd/gardener-extension-runtime-gvisor/app/app.go
- go.mod
- go.sum
- pkg/healthcheck/add.go
- vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/actuator.go
- vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/controller.go
- vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/healthcheck_actuator.go
- vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/inject.go
- vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/message_util.go
- vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/reconciler.go
- vendor/modules.txt
**How to categorize this PR?**
/area control-plane
/kind bug
Cherry-pick of #79 on release-v0.9.
Fixes #
```bugfix operator
The stale healthcheck conditions from the `runtime-gvisor` extension are now properly cleaned up.
```
```other dependency
The following dependency is updated:
- github.com/gardener/gardener: v1.65.0 -> v1.65.3
```
> [release-v0.9] Vendor `gardener@1.65.3` and add `ShootSystemComponentsHealthy` to `conditionTypesToRemove`

- cmd/gardener-extension-runtime-gvisor/app/app.go
- go.mod
- go.sum
- pkg/healthcheck/add.go
- vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/actuator.go
- vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/controller.go
- vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/healthcheck_actuator.go
- vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/inject.go
- vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/message_util.go
- vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/reconciler.go
- vendor/modules.txt
**How to categorize this PR?**
/area control-plane
/kind bug
For the reasoning, please check https://github.com/gardener/gardener/issues/6775#issuecomment-1432816749 and https://github.com/gardener/gardener/pull/7660.
We need to add the healthcheck controller back and add `ShootSystemComponentsHealthy` to `conditionTypesToRemove`.
Part of  https://github.com/gardener/gardener/issues/6775
```bugfix operator
The stale healthcheck conditions from the `runtime-gvisor` extension are now properly cleaned up.
```
```other dependency
The following dependency is updated:
- github.com/gardener/gardener: v1.65.0 -> v1.65.3
```
> Vendor `gardener@1.65.3` and add `ShootSystemComponentsHealthy` to `conditionTypesToRemove`

- charts/internal/gvisor-installation/templates/daemonset-containerd.yaml
This will prevent Daemonset to complain about `misscheduled pods found` for nodes that are scheduled to be `Scaledown`
Fixes #
```improvement operator
Added NoExecute/NoSchedule tolerations to the gvisor daemonset to prevent reporting of `misscheduled` pods on node scale-down operations.
```
> Add taint to daemonset

- Dockerfile
Updates the Alpine base images for the gvisor installation container to Alpine 3.17.4.
```other operator
The Alpine base images for the gVisor installation containers were updated to the latest 3.17.4 version.
```
> Update Alpine images to 3.17.4

- Dockerfile
Fix for CVE-2024-0727 (update alpine version for the gvisor installation container).
Fixes #
```improvement operator
Fix CVE-2024-0727
```
> Fix for CVE-2024-0727

- .gitignore
- Makefile
- hack/sast.sh
- pkg/apis/config/loader/loader.go
**How to categorize this PR?**
/kind cleanup
Following https://github.com/gardener/gardener/pull/9959, this PR enables Static Application Security Testing (SAST) with `gosec` on this repo.
```other developer
Static Application Security Testing (sast) with `gosec` got enabled on this repository.
```
> enable gosec for static code analysis

- .ci/check_and_bump_gvisor_version.py
- .ci/pipeline_definitions
Adds a script and a pipeline that checks for new/updated gVisor versions at regular intervals and files a pull request should a new version be found.
```improvement operator
NONE
```
> Add script and pipeline that automatically bumps gVisor version

- .ci/check_and_bump_gvisor_version.py
Fixes the compatibilitiy of the `check_and_bump_gvisor_version.py` script introduced in PR #184 with urllib3 v1.
Fixes #
```improvement operator
NONE
```
> Fix bump-gVisor script compatibility with urllib3 v1

- README.md
- charts/internal/gvisor-installation/values.yaml
- pkg/charts/charts_test.go
- pkg/charts/values.go
In order to be able to debug problems with Pods that use a `gVisor` RuntimeClass, it may be necessary to turn on debug logs for runsc by putting something like
```
[runsc_config]
debug = "true"
debug-log = "/var/log/runsc/%ID%/gvisor.log"
```
into `/etc/containerd/runsc.toml`. With this PR, it will be possible to provide a `debug: "true"` directive in the ProviderConfig for the gVisor runtime which will then configure `/etc/containerd/runsc.toml` accordingly.
```improvement user
If debugging of workloads in gVisor is required, runsc debug logs can be turned on by specifying `debug: "true"` in the gVisor providerConfig.
```
> Allow turning on runsc debug logs via providerConfig

- Makefile
- pkg/controller/actuator.go
- pkg/controller/actuator_delete.go
- pkg/controller/actuator_migrate.go
This PR sets the `keepObjects=true` on ManagedResources managed by this extensions when the corresponding ContainerRuntimes are migrated as part of control plane migration and then deletes them.
With this, the corresponding resources in the shoot will be kept and adopted by the ManagedResources that get deployed in the once the shoot's control plane once it is restored on the destination seed.
Fixes #128 
Keeping the PR as a draft until I test it with the [getting started locally with extensions setup](https://github.com/gardener/gardener/blob/master/docs/deployment/getting_started_locally_with_extensions.md)
Update: I successfully performed a control plane migration with the …
> Properly clean up `ManagedResources` during `migrate` phase of control plane migration.

- .github/ISSUE_TEMPLATE/support.md
- README.md
/kind enhancement
/area open-source
This PR switches all Slack references to the dedicated Gardener Project workspace.
Part of https://github.com/gardener/documentation/issues/606
```improvement operator
NONE
```
> Switch Slack references to Gardener workspace

- README.md
- charts/internal/gvisor-installation/values.yaml
- example/shoot.yaml
- pkg/apis/config/v1alpha1/register.go
- pkg/charts/charts_test.go
- pkg/charts/values.go
Adds support for the `nvproxy` config flag to enable gvisor pods to use NVIDIA GPUs.
Fixes #198 
> **Release note**:
```improvement operator
NVIDIA GPU support can be enabled by specifying `nvproxy: "true` in the gVisor providerConfig.
```
> NVIDIA GPUs support via nvproxy

- hack/api-reference/config.json
- pkg/controller/controller_test.go
Drop support for Shoots, Seeds and Gardens with Kubernetes version <= 1.28.
Part of https://github.com/gardener/gardener/issues/12409
N/A
```improvement operator
`runtime-gvisor` no longer supports Shoots with Кubernetes version <= 1.28.
```
> Drop support for Shoots with Kubernetes version <= 1.28

- .github/workflows/build.yaml
If using pull_request_target in conjunction with trusted-label, `trusted-checkout`-action attempts to remove `trusted`-label. In order to do so, `pull-requests: write`-permission is needed.
Fixes #276 
Issue resolved in other gardener repo here: https://github.com/gardener/dashboard/pull/2555/commits/1c8977dda50e5ef0334cb8412a9c9018da36f241
```improvement operator
NONE
```
> ci: fix permission for pull_request_target in conjunction with trusted label

- .github/workflows/bump-gvisor-version.yaml
Missing GH_TOKEN in fetch_version step
Fixes https://github.com/gardener/gardener-extension-runtime-gvisor/actions/runs/17369082701/job/49301075945#step:4:59
```improvement operator
NONE
```
> fix: use gh token in fetch version step from app
